version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    command: npm run dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ".:/app"
      - "./node_modules:/app/node_modules"
